//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISO
    {
        public PERMISO()
        {
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public decimal ID_PERMISO { get; set; }
        public decimal ID_MOTIVO { get; set; }
        public decimal ID_TIPOPERMISO { get; set; }
        public string ID_USUARIO { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual MOTIVO MOTIVO { get; set; }
        public virtual TIPO_PERMISO TIPO_PERMISO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
    }
}
