//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESOLUCION
    {
        public decimal ID_RESOLUCION { get; set; }
        public decimal ID_SOLICITUD { get; set; }
        public System.DateTime FECHA_RESOLUCION { get; set; }
        public string CODIGO { get; set; }
    
        public virtual SOLICITUD SOLICITUD { get; set; }
    }
}
