//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_PERMISO
    {
        public TIPO_PERMISO()
        {
            this.PERMISO = new HashSet<PERMISO>();
        }
    
        public decimal ID_TIPOPERMISO { get; set; }
        public string NOMBREPERMISO { get; set; }
        public decimal DIAS { get; set; }
    
        public virtual ICollection<PERMISO> PERMISO { get; set; }
    }
}
